'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/Button';
import { Card } from '@/components/Card';
import { Badge } from '@/components/ui/Badge';
import { MetricCard } from '@/components/ui/MetricCard';
import { PageHeader } from '@/components/ui/PageHeader';
import { generateQuiz, isDemoMode } from '@/services/api';
import { useAppStore } from '@/store/useAppStore';
import type { DepthLevel, Language } from '@/types';

export default function LessonPage() {
  const router = useRouter();
  const {
    currentLesson,
    currentTopic,
    depth,
    language,
    isLoading,
    setIsLoading,
    error: storeError,
    setError,
    setCurrentQuiz,
    clearQuizAnswers,
  } = useAppStore();

  useEffect(() => {
    if (!currentLesson) {
      router.push('/dashboard');
    }
  }, [currentLesson, router]);

  const handleGenerateQuiz = async () => {
    if (!currentLesson) {
      return;
    }

    setError(null);
    setIsLoading(true);
    clearQuizAnswers();

    try {
      const response = await generateQuiz({
        topic: currentTopic,
        depth: depth as DepthLevel,
        language: language as Language,
      });

      if (response.success && response.data) {
        setCurrentQuiz(response.data);
        router.push('/quiz');
        return;
      }

      setError(response.error || 'Failed to generate quiz.');
    } catch (error) {
      const message =
        error instanceof Error ? error.message : 'An unexpected error occurred.';
      setError(message);
    } finally {
      setIsLoading(false);
    }
  };

  if (!currentLesson) {
    return (
      <div className="space-y-6">
        <PageHeader
          eyebrow="Lesson"
          title="Preparing your lesson."
          description="If no lesson is available yet, the workspace will return you to the dashboard."
        />
        <Card className="flex min-h-[280px] items-center justify-center">
          <p className="text-sm text-text-secondary">Loading lesson...</p>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Lesson"
        title={currentTopic || currentLesson.coreConcept}
        description="The content is broken into readable sections so the learner can move from the core idea to the recap without losing context."
        status={
          isDemoMode
            ? 'Lesson content is served by the demo layer.'
            : 'Lesson content was generated by the API.'
        }
        action={
          <div className="flex flex-wrap gap-3">
            <Badge tone="primary">{depth}</Badge>
            <Badge tone="accent">{language}</Badge>
          </div>
        }
      />

      {storeError && (
        <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">
          {storeError}
        </div>
      )}

      <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
        <div className="space-y-6">
          <Card>
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.24em] text-text-secondary">
                  Core concept
                </p>
                <h2 className="mt-2 text-2xl font-semibold text-text-primary">
                  The big idea, reduced to one clear frame
                </h2>
              </div>
              <Badge tone="primary">Section 1</Badge>
            </div>
            <p className="mt-5 text-base leading-8 text-text-primary">
              {currentLesson.coreConcept}
            </p>
          </Card>

          <Card>
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.24em] text-text-secondary">
                  Step-by-step explanation
                </p>
                <h2 className="mt-2 text-2xl font-semibold text-text-primary">
                  Read it like a guided walkthrough
                </h2>
              </div>
              <Badge tone="accent">Section 2</Badge>
            </div>
            <p className="mt-5 text-base leading-8 text-text-primary">
              {currentLesson.explanation}
            </p>
          </Card>

          <Card>
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.24em] text-text-secondary">
                  Practical example
                </p>
                <h2 className="mt-2 text-2xl font-semibold text-text-primary">
                  See the concept in motion
                </h2>
              </div>
              <Badge tone="warning">Section 3</Badge>
            </div>
            <p className="mt-5 text-base leading-8 text-text-primary">
              {currentLesson.example}
            </p>
          </Card>

          <Card>
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.24em] text-text-secondary">
                  Summary
                </p>
                <h2 className="mt-2 text-2xl font-semibold text-text-primary">
                  Compact enough to remember after the session
                </h2>
              </div>
              <Badge tone="success">Section 4</Badge>
            </div>
            <p className="mt-5 text-base leading-8 text-text-primary">
              {currentLesson.summary}
            </p>
          </Card>

          <div className="flex flex-col gap-3 sm:flex-row">
            <Button variant="secondary" onClick={() => router.push('/dashboard')}>
              New topic
            </Button>
            <Button onClick={handleGenerateQuiz} isLoading={isLoading} fullWidth>
              {isLoading ? 'Generating quiz...' : 'Generate quiz'}
            </Button>
          </div>
        </div>

        <div className="space-y-6">
          <MetricCard
            label="Learning mode"
            value={`${depth} | ${language}`}
            detail="The same context flows directly into the quiz so the experience feels connected."
            accent="cyan"
          />

          <Card>
            <p className="text-xs font-semibold uppercase tracking-[0.24em] text-text-secondary">
              Lesson snapshot
            </p>
            <div className="mt-4 space-y-3">
              {[
                { label: 'Topic', value: currentTopic || currentLesson.coreConcept },
                { label: 'Depth', value: depth },
                { label: 'Language', value: language },
                { label: 'Next step', value: 'Generate quiz' },
              ].map(item => (
                <div
                  key={item.label}
                  className="rounded-2xl bg-surface-muted px-4 py-3"
                >
                  <p className="text-xs font-semibold uppercase tracking-[0.2em] text-text-secondary">
                    {item.label}
                  </p>
                  <p className="mt-2 text-sm font-medium text-text-primary">
                    {item.value}
                  </p>
                </div>
              ))}
            </div>
          </Card>

          <Card>
            <p className="text-xs font-semibold uppercase tracking-[0.24em] text-text-secondary">
              Reading experience
            </p>
            <ul className="mt-4 space-y-3 text-sm leading-6 text-text-primary">
              <li className="rounded-2xl bg-surface-muted px-4 py-3">
                Dark blue headings anchor each section.
              </li>
              <li className="rounded-2xl bg-surface-muted px-4 py-3">
                Neutral body text keeps the content easy to scan.
              </li>
              <li className="rounded-2xl bg-surface-muted px-4 py-3">
                Spacing does the work instead of heavy borders.
              </li>
            </ul>
          </Card>
        </div>
      </div>
    </div>
  );
}
